openapi: 3.0.0
info:
  title: cost-analyzer
  version: '1.0'
servers:
  - url: 'http://localhost:8000'
paths:
  '/costs/{clientId}':
    parameters:
      - schema:
          type: string
        name: clientId
        in: path
        required: true
    post:
      summary: ''
      operationId: createNewCost
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CostDTO'
  '/costs/{clientId}/all':
    parameters:
      - schema:
          type: string
        name: clientId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CostsDTOWrapper'
      operationId: getAllCosts
  /category/all:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTOWrapper'
      operationId: getAllCategory
components:
  schemas:
    CostDTO:
      title: CostDTO
      type: object
      properties:
        category:
          type: string
        expenditure:
          type: number
      required:
        - category
        - expenditure
    CostsDTOWrapper:
      title: CostsDTOWrapper
      type: object
      properties:
        costList:
          type: array
          items:
            $ref: '#/components/schemas/CostDTO'
      required:
        - costList
    CategoryDTO:
      title: CategoryDTO
      type: object
      properties:
        categoryName:
          type: string
    CategoryDTOWrapper:
      title: CategoryDTOWrapper
      type: object
      properties:
        categoryList:
          type: array
          items:
            $ref: '#/components/schemas/CategoryDTO'
      required:
        - categoryList
  requestBodies: {}
